import type { FarmState } from "./types";

export const journey = [
  {
    chapter: "一小片属于你的天地",
    title: "先给小羊一个家",
    text: "这里还只是一片空地。我留下了木料和图纸，走到木桩旁，搭起你的第一座羊舍吧。",
    task: "在木桩标记处搭建羊舍",
    action: "去搭建羊舍",
    art: "shelter",
    person: 0,
    name: "青苔奶奶",
    unlock: "羊舍与羊群手册",
  },
  {
    chapter: "一小片属于你的天地",
    title: "迎接第一位室友",
    text: "新家准备好了。棉花糖是一只温柔的云朵羊，它正在等一个愿意照顾它的人。",
    task: "领养第一只云朵羊 · 110 金币",
    action: "迎接棉花糖",
    art: "bell",
    person: 0,
    name: "青苔奶奶",
    unlock: "认识第一只羊",
  },
  {
    chapter: "认识一团小小的云",
    title: "先和它打个招呼",
    text: "刚到陌生地方，它有一点紧张。选中「摸摸」，靠近小羊按 E，或者直接点一点它。",
    task: "轻轻摸摸棉花糖",
    action: "去认识小羊",
    art: "bell",
    person: 0,
    name: "青苔奶奶",
    unlock: "好心情",
  },
  {
    chapter: "认识一团小小的云",
    title: "小肚子也要被照顾",
    text: "看，它已经喜欢你了。饱腹感会慢慢下降，试试新出现的喂食工具，给它一份香喷喷的牧草。",
    task: "喂小羊吃一份饲料",
    action: "准备好饲料",
    art: "feed",
    person: 0,
    name: "青苔奶奶",
    unlock: "喂食与饱腹感",
  },
  {
    chapter: "认识一团小小的云",
    title: "收下云朵的礼物",
    text: "健康快乐的成年羊会长出蓬松绒毛。棉花糖的羊毛已经长好了，轻轻剪下来，它会清爽很多。",
    task: "用剪毛工具收获第一份羊毛",
    action: "拿起小剪刀",
    art: "wool",
    person: 2,
    name: "织匠阿棕",
    unlock: "剪毛与绒毛生长",
  },
  {
    chapter: "把日子种进泥土",
    title: "一小块田，许多期待",
    text: "谢谢你的羊毛！我送来了一套菜畦木框。把它铺在河边，以后就能自己种牧草了。",
    task: "在河边搭建第一片菜畦",
    action: "去搭建菜畦",
    art: "timber",
    person: 1,
    name: "花匠小葵",
    unlock: "田间手记与种子",
  },
  {
    chapter: "把日子种进泥土",
    title: "种下一点点绿色",
    text: "先从好养的三叶草开始吧。选好种子，点一块空田，把小小的期待种进去。",
    task: "播下一包三叶草种子",
    action: "选择三叶草",
    art: "seed",
    person: 1,
    name: "花匠小葵",
    unlock: "播种",
  },
  {
    chapter: "把日子种进泥土",
    title: "给小苗一场雨",
    text: "种子还在等水呢。给刚种好的田浇一点水，它才会开始生长。下雨天，天空也会帮忙。",
    task: "给刚种下的三叶草浇水",
    action: "拿起浇水壶",
    art: "clover",
    person: 1,
    name: "花匠小葵",
    unlock: "浇水与生长",
  },
  {
    chapter: "把日子种进泥土",
    title: "等一小会儿，收获春天",
    text: "三叶草大约 45 秒就会长好。等待的时候可以陪陪小羊；田边亮起金色光圈，就能收获啦。",
    task: "收获第一批三叶草",
    action: "看看小苗",
    art: "clover",
    person: 1,
    name: "花匠小葵",
    unlock: "收获与背包",
  },
  {
    chapter: "风会把好消息带来",
    title: "邻居也在等你的丰收",
    text: "山坡那边的小兔子需要三份三叶草。把丰收装进信篮，你会收到金币，也会认识新的朋友。",
    task: "完成第一份邻里委托",
    action: "打开委托信",
    art: "letter",
    person: 1,
    name: "花匠小葵",
    unlock: "邻里委托与杂货铺",
  },
  {
    chapter: "带着羊，一起出门",
    title: "围栏外，还有一整个春天",
    text: "铃兰花坡的门打开了。回到羊舍门口集合，带小羊去吃新鲜草，再到泉边喝水，最后一起回家。",
    task: "在羊舍门口开始一次放牧",
    action: "回门口集合",
    art: "bell",
    person: 3,
    name: "巡林员阿岚",
    unlock: "铃兰花坡与放牧",
  },
  {
    chapter: "带着羊，一起出门",
    title: "今天的路，要一起走完",
    text: "慢慢走，小羊会跟着领队。到花坡吃饱草，再去西边的清泉饮水；最后记得一只不少地带回羊舍。",
    task: "吃草、饮水，再带羊群归圈",
    action: "查看放牧路线",
    art: "clover",
    person: 3,
    name: "巡林员阿岚",
    unlock: "轮牧、饮水与归圈",
  },
  {
    chapter: "小小的家，慢慢长大",
    title: "期待一团新的绒毛",
    text: "你已经会照顾羊啦。给它找一位异性伙伴，喂饱、摸摸，准备好后就能迎接小羊羔。",
    task: "领养伙伴并迎来第一只羊羔",
    action: "看看我的羊群",
    art: "wool",
    person: 0,
    name: "青苔奶奶",
    unlock: "繁育、性格与品种图鉴",
  },
  {
    chapter: "沿着小路，去更远的地方",
    title: "蘑菇林的小秘密",
    text: "河对岸的林间小路通了。那里藏着三簇蘑菇，走近后轻轻采下；它们会成为下一段旅程的礼物。",
    task: "在蘑菇秘林发现三簇蘑菇",
    action: "走进蘑菇秘林",
    art: "mushroom",
    person: 3,
    name: "巡林员阿岚",
    unlock: "蘑菇秘林与野外采集",
  },
  {
    chapter: "沿着小路，去更远的地方",
    title: "为星光准备一个家",
    text: "高地的旧营地需要修缮。长到牧场等级 3，备好 120 金币、三朵蘑菇和三根胡萝卜，我们就能打开山路。",
    task: "修复星落高地的栖息地",
    action: "看看高地计划",
    art: "shelter",
    person: 3,
    name: "巡林员阿岚",
    unlock: "星落高地与夜间惊喜",
  },
  {
    chapter: "你的牧场故事，才刚刚开始",
    title: "今天，想做哪一件小事？",
    text: "新的风景、花草和羊朋友都在等你。轮流去放牧、完成邻里的心愿，把这里慢慢变成你喜欢的样子。",
    task: "照顾、探索，收集更多软乎乎",
    action: "翻开山谷地图",
    art: "letter",
    person: 0,
    name: "青苔奶奶",
    unlock: "自由牧场生活",
  },
] as const;

export const cropUnlock: Record<string, number> = {
  clover: 6,
  carrot: 9,
  wheat: 10,
  daisy: 12,
  lavender: 13,
  pumpkin: 14,
  moonflower: 15,
};
export const toolUnlock: Record<string, number> = {
  pet: 2,
  feed: 3,
  shear: 4,
  plant: 6,
  water: 7,
  harvest: 8,
};
export const panelUnlock: Record<string, number> = {
  flock: 1,
  garden: 6,
  shop: 9,
  journal: 12,
  orders: 9,
  map: 10,
};

export function grazingTask(state: FarmState) {
  if (!state.grazing.active) return "回到羊舍门口，开始今天的放牧";
  if (state.grazing.grazeSeconds < 20)
    return `在铃兰花坡吃草 ${Math.min(20, Math.floor(state.grazing.grazeSeconds))} / 20 秒`;
  if (!state.grazing.watered) return "带小羊到花坡西侧的清泉饮水";
  return "都吃饱喝足啦，带羊群回基地归圈";
}
